<a href="https://colab.research.google.com/github/ayoub-bakr/pytorch-/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[   0,    1, 4141,    3,    4],
        [   5,    6,    7,    8,    9]])

In [12]:
my_torch5 [2] = 4141
my_torch5

tensor([   0,    1, 4141,    3,    4,    5,    6,    7,    8,    9])

In [15]:
my_torch5[2]

tensor(4141)

In [21]:
my_torch5[5:8]

tensor([5, 6, 7])

TENSOR MATH OPERATIONS

Add, Subtract, Multiply, Divide, Remainders, Exponents
Shorthand and uh, Longhand
Reassignment

In [27]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [28]:
# Add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [29]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [31]:
# Subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [32]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [33]:
# Multiply
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [34]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [35]:
# Divide
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [36]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [37]:
# Remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [39]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [40]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])