<a href="https://colab.research.google.com/github/ayoub-bakr/pytorch-/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[   0,    1, 4141,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
my_torch5 [2] = 4141
my_torch5

tensor([   0,    1, 4141,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch5[2]

tensor(4141)

In [ ]:
my_torch5[5:8]

tensor([5, 6, 7])

TENSOR MATH OPERATIONS

Add, Subtract, Multiply, Divide, Remainders, Exponents
Shorthand and uh, Longhand
Reassignment

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# Add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# Multiply
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# Divide
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# Remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [4]:
# Create a Model Class that inherits nn.Module
class Model(nn.Module):
  # Input layer (4 features of the flower) -->
  # Hidden Layer1 (number of neurons) -->
  # H2 (n) -->
  # output (3 classes of iris flowers)
  def __init__(self,in_features = 4 , h1 = 8 , h2 = 9 , out_features = 3):
    super(). __init__()
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)
    return x

In [7]:
# Pick a manual seed for randomization
torch.manual_seed(41)
model = Model()

In [8]:
print(model)

Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)


In [9]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
my_df = pd.read_csv(url)

In [13]:
my_df.tail()

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [14]:
print("عدد الكلاسات:", my_df['variety'].nunique())
print("أسماء الكلاسات:", my_df['variety'].unique())

عدد الكلاسات: 3
أسماء الكلاسات: ['Setosa' 'Versicolor' 'Virginica']


In [18]:
my_df ['variety'] = my_df['variety'].replace({'Setosa': 0 ,'Versicolor': 1 ,'Virginica': 2})

/tmp/ipython-input-3829640232.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  my_df ['variety'] = my_df['variety'].replace({'Setosa': 0 ,'Versicolor': 1 ,'Virginica': 2})


In [20]:
my_df

sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [21]:
# Train Test Split!  Set X, y
X = my_df.drop('variety', axis=1)
y = my_df['variety']

In [22]:
from sklearn.model_selection import train_test_split

In [24]:
# Train Test Split
X_train ,X_test, y_train, y_test = train_test_split(X , y, test_size= 0.2 , random_state=41)

In [33]:
# Convert X features to float tensors
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)